version: '3'
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: container_nginx
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: container_php
    volumes:
      - ./app:/var/www/app
    ports:
      - 9000:9000
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: container_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    container_name: container_adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    container_name: container_composer
    entrypoint: composer
    volumes:
      - ./app:/app
    working_dir: /app

volumes:
  db-data:
