version: '3'
services:
  web:
    image: nginx:latest
    container_name: container_app
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    image: php:7.4-fpm
    container_name: container_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: container_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer:latest
    container_name: container_adminer
    ports:
      - 8081:8080
    depends_on:
      - db

  composer:
    image: composer:latest
    container_name: container_composer
    volumes:
      - ./app:/app
    working_dir: /app