version: '3'
services:
  web:
    image: nginx:latest
    container_name: container_app
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  php:
    image: php:8.1-fpm
    container_name: container_php
    volumes:
      - ./app:/var/www/app
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: container_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    build:
      context: .
      dockerfile: Dockerfile.adminer
    container_name: container_adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres

  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    container_name: container_composer
    entrypoint: composer install
    volumes:
      - ./app:/app
    working_dir: /app